# Theme: Beautiful Jekyll

# --- Required options --- #

title: LAB02 Research
author: LAB02 Research

# --- List of links in the navigation bar --- #

navbar-links:
  HASS.Agent:
    - About: "hassagent"
    - Docs: "https://hassagent.readthedocs.io/en/latest/"
    - Source: "https://github.com/LAB02-Research/HASS.Agent"
  About Us: "aboutus"
  Repository: "https://github.com/LAB02-Research/"

# --- Logo --- #

avatar: "/assets/img/rocket_logo.png"
round-avatar: true
title-img: "/assets/img/logo_full_small.png"

# --- Footer social media links --- #

social-network-links:
  email: "lab02research@outlook.com"
  rss: true
  github: LAB02-Research
  reddit: LAB02-Research
  discord: invite/nMvqzwrVBU 

rss-description: LAB02 Research activity feed.

# --- General options --- #

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

url-pretty: "lab02-research.org"
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
keywords: "home,assistant,windows,companion,app,hass,agent,domotica,tech,development,lab02,research,automation"

# --- Colours / background image --- #

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

#site-css:
#  - "/assets/css/custom-styles.css"

#site-js:
#  - "/assets/js/custom-script.js"

# --- Misc --- #

date_format: "%B %-d, %Y"
timezone: "Europe/Amsterdam"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false  
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189

